### ISSUE TITLE
Telework: Send manager's IDIR and GUID to the ODS on submission

### ISSUE THREAD

**Issue by schuyt** [bcgov/digital-journeys#208]
I would like to send the manager's IDIR and GUID to the ODS on the submission of the telework form, so that I have the info available for reporting later.

**Acceptance Criteria**

- When the Telework form is approved by a supervisor (and submitted) both the managers IDIR and GUID get sent to the ODS.

**Notes:**
- Currently only the submitters IDIR and GUID are sent.
- See: https://github.com/bcgov/digital-journeys/blob/6e0cca4f56a1910a30d46083fcb72a16b498375e/docs/workflows.md

**Comment by Stella-Archer** [comment]
@DonMoffatt could you fill out the employee portion of the tele work in test so we can get a test to Patrick?

**Comment by DonMoffatt** [comment]
I hope to do that before the 11 a.m. meeting.

**Comment by DonMoffatt** [comment]
I sent a submission. I was puzzled why I saw the manager's portion below the submit button. Shouldn't that be hidden?

**Comment by Stella-Archer** [comment]
Correct version in dev: https://digital-journeys-dev.apps.silver.devops.gov.bc.ca/form/6245258a5302ccaf000035e7

**Comment by jizhaogit** [comment]
has some issues while doing form submission. turn back to check the API calling

**Comment by T854236** [comment]
Hi, can you confirm if this is ready for testing or testing has already been done?  To confirm, there are no new records in ODS in May.

**Comment by jizhaogit** [comment]
Listener  ExtractManagerGuid.java is created in https://github.com/bcgov/digital-journeys/tree/main/forms-flow-bpm/src/main/java/org/camunda/bpm/extension/hooks/listeners

need bpmn workflow updates

**Comment by Stella-Archer** [comment]
Iman working on supervisor approval block

**Comment by Stella-Archer** [comment]
Iman working with Simon to solve issue on local then moving dev

**Comment by iman-jamali-fw** [comment]
My local issue was fixed thanks to Simen. I had to reload `Formio Access Token Cache (Internal)` from the Camunda dashboard.

 ![Screen Shot 2022-05-12 at 2.41.11 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/0e6c89c5-6ab4-4771-b5f7-0d813b532682)

**Comment by iman-jamali-fw** [comment]
@Stella-Archer Ticket is ready for testing on dev.

**Comment by iman-jamali-fw** [comment]
@T854236 Two fields are send to ODS are name under `managerGuid` and `managerIdir`.

**Comment by T854236** [comment]
Hi, I saw some tests this morning.  Unfortunately the values are still missing.

![image.png](https://images.zenhubusercontent.com/626979332cf51c6ab3c77983/60797f3d-d003-4dea-8caa-a6bb760daa3d)

**Comment by T854236** [comment]
The field names in the endpoint can be found here: https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_app_telework_info/

They are manager_guid and manager_idir.

**Comment by Stella-Archer** [comment]
I tried this a couple of times today.
1/ I was able to 'approve' and 'submit' in DEV but 
2/ there was no validation message to and as a manager i was send to a blank space in 'tasks'
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/bc2f2dc4-dda8-4785-8491-75be771ceffb)
2/didn't receive a copy of the uploaded approval file in my manager email

**Comment by iman-jamali-fw** [comment]
Hi @T854236 , Thanks for the note on field names. I updated them to manager_guid and manager_idir. Can you try again to see if values are received on ODS end? Thank you

**Comment by Stella-Archer** [comment]
tested again with Meghan @ 4:30pm PST same results

**Comment by T854236** [comment]
Reviewed the test that you've done @Stella-Archer, in the data warehouse we see the manager information as per below.  I noticed that on some tests, you approved your own submission.

![image.png](https://images.zenhubusercontent.com/626979332cf51c6ab3c77983/dc10edc5-c31a-48b6-8899-98ecaac6e2d0)

**Comment by iman-jamali-fw** [comment]
Looking into the issue with "uploaded file is missing from supervisor email".

**Comment by iman-jamali-fw** [comment]
@Stella-Archer 
The issue with the missing uploaded file in the email is fixed :)
The supervisor 
![Screen Shot 2022-05-16 at 4.28.45 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/0c363d43-483f-44f2-a722-1f644bb6df1c)should be able to see the uploaded file as an attachment in the email.
