### ISSUE TITLE
Mat/Pat : Parental leave partner info logic 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#884]
**User Story**
As an applicant I should be able to provide my partner's info using their email address so that I do not have to enter all their information manually. 

**Design** 
[Get partner Info](https://miro.com/app/board/uXjVOWaGSE0=/?moveToWidget=3458764543687588212&cot=14)

**Acceptance Criteria**
- [x] Applicant should be able to use their partners email & employee number to fetch their information
    - [x] The following  gov email address should be allowed.  `
"gov.bc.ca", 
 "bcest.bc.ca", 
"bchumanrights.ca", 
"crtbc.ca", 
"destinationbc.ca", 
"eaat.ca", 
"elections.bc.ca", 
"iiobc.ca", 
"lrb.bc.ca", 
"wao-bc.org", 
"eao-bc.org", 
"wcat.bc.ca", 
"royalbcmuseum.bc.ca", 
"rcybc.ca", 
"wao-bc.org"`
    - [x] Employee number should be a valid 6 _(?)_ digit number 
    - [x] Both fields are required
    - [x] Employee number should be fetched for the email address provided. If employee number fetched using email does not match the employee number entered by the applicant the following error should be shown 

`Employee number entered does not match our records for the email address provided. Please ensure that your partner's email address and employee number is correct`

- [x] Applicant should be able to see Name, Ministry and Department for their partner
    - [x] These fields should not be editable
-  [ ] Applicant must confirm info is correct or a service request has been raised via radio button
      - Radio button is mandatory, however validate only on form submission, not on moving to next page

**Comment by iman-jamali-fw** [comment]
@T854236 
Hey Patrick, I have two questions for you.
1. How can I get employee's ministry from ODS? When I hit the `https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demographic` I get some data about `level1_program`, `level2_division` and `level3_branch`. Not sure if they translate into ministry.

2. Can the [Telework endpoint](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_employee_demographic) be reused for mat-pat form users? Or it's better, from the ODS stand point, to create a separate endpoint?

**Comment by iman-jamali-fw** [comment]
@T854236 

Also found [this endpoint](https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/$metadata#Datamart_Telework_meta_dept_org_levels) returning an object as below. Is this accurate and can I use this to get an employee's ministry name? perhaps by referencing `DepartmentID` which is also available on the `Datamart_Telework_employee_demographic` endpoint?
```json
{
  "DepartmentID": "002-0000", 
  "Level1": "NON CORE", 
  "Level2": "Legislation", 
  "Level3": "CONVERSION", 
  "Level4": null, 
  "Organization": null
}
```

**Comment by T854236** [comment]
@iman-jamali-fw 

DEV ODS is old, we can perform a refresh if you would like.

**Comment by T854236** [comment]
@iman-jamali-fw 

DEV has been refreshed now.

**Comment by iman-jamali-fw** [comment]
@T854236 
Thank you for updating the endpoint. 

Could you help me find out which field is the employee's **ministry** and which one is the **department**?

**Comment by T854236** [comment]
@iman-jamali-fw 

you can use organization field as ministry, the department would be level1, level2, level3 or level4 depending on how deep/big the departments are.

**Comment by EduardoRamirezBC** [comment]
Blocking: connection to ODS

**Comment by iman-jamali-fw** [comment]
@MeghanStothers  @Stella-Archer 

Question: Can you help me figure out which field from employee information(coming from ODS) best represents the department of that employee?

Best on what I learned from Patrick so far, ODS returns that information in four fields, level1, level2, level3, and level4 depending on how deep/big the departments are. For example, for someone in your department it returns:
```json

level1_program: "Human Resources Services and Solutions"
level2_division: "Operational Strategies & Integration Services "
level3_branch: "Op Start & Integration Serv"
```

**Comment by MeghanStothers** [comment]
I think the best answer is "leve13_branch"  (that is, if "department" is the same as "branch")

**Comment by Stella-Archer** [comment]
@MeghanStothers it's weird but "level3_branch": "Op Start & Integration Serv" 
looks like the same, but badly abbreviated version of"
level2_division": "Operational Strategies & Integration Services ",
when in fact our branch under OSIS should be 
"Online Strategies and Business Design"
which makes me think the data at "level3_branch": may not be all that great and a partner may not recognize the info. 
The data at the Division level "level2_division":  seems clearer, a user could read and understand if it was served up on the page for them to confirm that's where their partner worked.

**Comment by MeghanStothers** [comment]
@iman-jamali-fw "level2_division" is our answer :)

**Comment by iman-jamali-fw** [comment]
@MeghanStothers @Stella-Archer 
I'll use "level2_division". Thank you.

**Comment by iman-jamali-fw** [comment]
@Stella-Archer @fazil-ey 

This is ready for testing on TEST.

**Comment by ayushdamani** [comment]
![Screenshot (10).png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/598ad54c-cd42-40f0-b450-c0d0219865e2)

**Comment by fazil-ey** [comment]
@iman-jamali-fw seeing a network error when hitting get info. This is persistent since last week

**Comment by iman-jamali-fw** [comment]
@fazil-ey @ayushdamani 

Just tried and it seems working again. Can you please try again?
![Screenshot 2023-04-25 at 9.55.16 AM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/a32917cc-c3d1-4703-9e2c-222738a85808)

**Comment by fazil-ey** [comment]
Working now! 

A couple of things  - 
- Can we show the section following "Get Info" button, after the information is fetched successfully. 

- Can we update the error message to the one mentioned in the ticket `Employee number entered does not match our records for the email address provided. Please ensure that your partner's email address and employee number is correct`

**Comment by Andrew-Vargas-bcgov** [comment]
@iman-jamali-fw 
updated error message.
Hid components below Get Info button and set them to unhide after successful fetch.

**Comment by iman-jamali-fw** [comment]
@fazil-ey 

Could you take another look and check Andrew's changes to the error message? Thank yoiu

**Comment by ayushdamani** [comment]
I am receiving a 'network error' @iman-jamali-fw 

![Screenshot 2023-05-01 150229.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/0a92f29d-5bdb-484f-ab83-3db6a414f775)

**Comment by iman-jamali-fw** [comment]
@ayushdamani 

The issue is fixed and it should work again for PSA and non-PSA employees. Please try again. Thank you

**Comment by ayushdamani** [comment]
Thank you for your responsiveness! @iman-jamali-fw 

Tested and verified:
- 'Get info' button when clicked shows Name, Ministry and Department.
- Radio button works.

![Screenshot 2023-05-02 135736.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/d5c3b28b-0f19-41ce-9857-53c72afbb7fe)

One small suggestion - could we change the radio buttons so the user can only select one of the two options? I'm not sure if that matters.
![Screenshot 2023-05-02 143838.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/b45fe145-32d5-43b3-a593-44246b9b4487)

**Comment by iman-jamali-fw** [comment]
@ayushdamani  Good suggestion. I'll leave it for Fazil to comment @fazil-ey

**Comment by fazil-ey** [comment]
@iman-jamali-fw  this must be a radio button as its an either/or, it cannot be both

**Comment by fazil-ey** [comment]
Bugs found in test environment
**- AC 1.4 the error message is still incorrect**
![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/131e824b-2785-474b-93b0-3433a98ffd57)

**- AC 3.1 The radio button is not being validated on form submission**
[Screen Recording](https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-06-09%20at%201.32.23%20PM.mov?csf=1&web=1&e=0Vajsy)

- On the first try the wrong employee id did not trigger the error message but an empty parental leave details section
![Screen Shot 2023-06-09 at 1.37.35 PM.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/104cff4c-851d-4655-9383-5536c56f0016)
[Screen Recording](https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Paternity/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-06-09%20at%201.37.15%20PM.mov?csf=1&web=1&e=2r1gEY)

UX improvement
- Can we remove the section with partner details if another search is made?

**Comment by Andrew-Vargas-bcgov** [comment]
1) the error message is correct.
2) this will be addressed in #1197. feature was temporarily removed when we changed custom submit buttons.
3) fixed.
4) added change. Does it work like you want?

**Comment by ayushdamani** [comment]
Thank you Andrew!

Error message has been updated - 
![Screenshot 2023-06-19 052957.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/b3a47ee6-22cd-45b6-9c0d-8cbe6b93be51)

Radio button is now being validated upon submission - 
![Screenshot 2023-06-19 053129.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/bf517eb2-a823-484e-bbd9-e23f3be656bd)

@fazil-ey could you please you check the updated UX?

**Comment by fazil-ey** [comment]
@ayushdamani behaviour of the radio button isnt correct - "Radio button is mandatory, however validate only on form submission, **_not on moving to next page_**"

**Comment by ayushdamani** [comment]
My bad sir! Thank you for the clarification.

Moving the ticket back to Peer/Dev Review.

**Comment by ayushdamani** [comment]
this change is happening in ticket #1197

**Comment by fazil-ey** [comment]
Tested & works. Added a UX improvement in #1197
