### ISSUE TITLE
1.10 Only latest draft form data available on frontend

### ISSUE THREAD

**Issue by Andrew-Vargas-bcgov** [bcgov/digital-journeys#936]
All drafts are showing in the Drafts tabs, but only the most recent draft created, populates data. Drafts saved from edit page will also persist their data.

steps to recreate:

1. Start a new 1.10 form and enter some data and save the draft.
2. Create a second 1.10 form, enter some different data, and save the draft.
3. Go to drafts tab and try to view both forms.
4. Only one will have data.
5. There is also a chance that the data from the one form that persisted the data does not populate until a refresh.

Don has a demo at 4pm today to show the union the new form. He is the one that found the bug as he was pulling up one of his saved drafts.

**Comment by iman-jamali-fw** [comment]
@morezooomm @Andrew-Vargas-bcgov 
This should be fixed on TEST. Could you please test it out after a hard-refresh on your browser to make sure you have the latest version of the TOOL? Thank you

**Comment by morezooomm** [comment]
Iman,

How do I do a “hard refresh” of my browser?

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***

**Comment by iman-jamali-fw** [comment]
@morezooomm 
Please either follow the instruction below or simply open a private/incognito page on your browser and then go to the [TEST](https://digital-journeys-test.apps.silver.devops.gov.bc.ca/).
![Screenshot 2023-02-21 at 12.31.22 PM.png](https://images.zenhubusercontent.com/61ddc48547f476ed3f35ca28/d41f3666-1f10-4d51-aabb-9bfe6d4488b5)

**Comment by morezooomm** [comment]
Sorry, I don’t see any “instructions below” on how to do a hard refresh of my browser.

I have also never opened a private/incognito page on my browser, so not sure how to do that either.

I did test the site with the link you provided below and the problem is still there for me.  The moment I click on a draft form, it jumps me to a new form.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***

**Comment by iman-jamali-fw** [comment]
@morezooomm 

No problem, I think the instruction which was an image didn't load on your side. 
Please let me know which browser and OS (Windows or Mac) are you using.

**Comment by morezooomm** [comment]
I am using Microsoft Edge on Windows.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***

**Comment by iman-jamali-fw** [comment]
@morezooomm 
To hard refresh Edge on Windows:
- Hold the Ctrl key and click the Refresh button.
- Or, hold the Ctrl key and press the F5 key.

OR to open the TEST in a `InPrivate` window in Edge, please select and hold (right-click) [TEST LINK](https://digital-journeys-test.apps.silver.devops.gov.bc.ca/form) and select Open link in InPrivate window.

**Comment by morezooomm** [comment]
I did a refresh of the browser but the same problem still exists.

I followed the directions below to launch a private browser, but didn’t get that option available.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***

**Comment by fazil-ey** [comment]
Not on issue, Iman & Don connected on Feb 22 and did not encounter this issue

**Comment by morezooomm** [comment]
Agreed, we can close this one.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

Government confidentiality and privilege requirements apply to this message and any attachments.  If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use is strictly prohibited. If you are not the intended recipient, please notify the sender immediately, and delete this message and any attachments from both your inbox and deleted items folder.
***@***.***
